import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import { visualizer } from "rollup-plugin-visualizer";

// Dev: proxy /api to the FastAPI backend (single origin → no CORS, no mixed content).
// Backend runs on 5433 so v2 coexists with the live Flask app on 5432 until cutover.
// The proxy target is `VITE_API_TARGET` (default :5433) so the SAME config serves both the local
// Windows dev backend AND emma's isolated DEV instance, which points at its own backend on :5434
// (D32 — prod :5433/~/.ctrl-b vs dev :5434/~/.ctrl-b-dev). No hardcoded port branch.
// PWA is wired here; the real manifest/precache tuning is Phase 9 (kept minimal for now).
//
// Bundle analyzer (F12 in docs/UI_AUDIT.md): `npm run build` always writes `dist/stats.html`
// (gzip + brotli sizes). Open it after a build to see exactly what's heavy before deciding
// on F6 (code-splitting) / F7 (lucide-react audit).
export default defineConfig({
  plugins: [
    react(),
    visualizer({
      filename: "dist/stats.html",
      template: "treemap",
      gzipSize: true,
      brotliSize: true,
      // Don't auto-open the report — it's a build artifact, opened on demand.
      open: false,
    }),
    VitePWA({
      registerType: "autoUpdate",
      devOptions: { enabled: false },
      manifest: {
        name: "ctrl-b",
        short_name: "ctrl-b",
        // Install/splash colors — a D51 DOCUMENTED MIRROR of the DEFAULT theme's `--bg` (cosmos,
        // src/themes/cosmos/tokens.css `#0a0a0d`), kept in step with index.html's <meta name="theme-color">.
        // Static by design: no theme-switch-driven update (recorded as later polish, out of V0).
        theme_color: "#0a0a0d",
        background_color: "#0a0a0d",
        display: "standalone",
        // PWA icon fan-out (F11). Generated by `scripts/gen-pwa-icons.mjs` from
        // `src/assets/vapor-logo.png` (the in-app logo became a bundled asset at D51 V4).
        // - 192/256/512 cover Android home-screen densities + browser install prompts.
        // - The maskable variant fits the brand into the 80% safe zone so Android's circle/squircle
        //   crop never clips it (W3C maskable spec).
        icons: [
          { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
          { src: "/icon-256.png", sizes: "256x256", type: "image/png", purpose: "any" },
          { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
          {
            src: "/icon-maskable-512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
      },
      workbox: {
        // Never cache /api responses — they're live state and mutations.
        navigateFallbackDenylist: [/^\/api\//],
        // The plugin default (js/css/html) PLUS vapor's bundled logo (D51 V4 close-out, sweep M2):
        // with cosmos the default, a fresh PWA gone offline may never have fetched the logo before
        // the first switch to vapor — without this entry the mark renders blank. Targeted glob, not
        // image-wide.
        //
        // CORRECTION (D52 §10.4, verified against the built artifact): the old note here claimed the
        // cosmos art set "stays runtime-cached". It is not — this repo has NO `runtimeCaching` rules at
        // all, so every theme's art and woff2 rely on the plain browser HTTP cache when offline. The
        // repo's first `runtimeCaching` routes (woff2 CacheFirst, `/api/media/` StaleWhileRevalidate —
        // never CacheFirst, those files are owner-mutable) land at G5 with their own gate, per council M8.
        //
        // `dist/stats.html` is the rollup-visualizer BUILD REPORT (~290 KB), not part of the app — the
        // bare `**/*.html` sweeps it into the precache manifest, where it costs every install its size
        // for a file nothing ever requests. Excluded here rather than by narrowing the html glob, so a
        // real future .html entry point is still picked up automatically.
        globPatterns: ["**/*.{js,css,html}", "assets/vapor-logo-*.png"],
        globIgnores: ["**/stats.html"],
      },
    }),
  ],
  server: {
    host: "0.0.0.0",
    port: 5173,
    // Accept any Host header. Vite (>=5.4) otherwise rejects non-localhost/IP hosts as a
    // DNS-rebinding guard, which blocks reaching the dev server by machine name (e.g.
    // http://corsair:5190) or the Tailscale Serve *.ts.net FQDN. Safe here: tailnet-only,
    // no public bind (AGENTS.md §6 security model).
    allowedHosts: true,
    proxy: { "/api": process.env.VITE_API_TARGET || "http://127.0.0.1:5433" },
  },
});
