import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import { visualizer } from "rollup-plugin-visualizer";

// Dev: proxy /api to the FastAPI backend (single origin → no CORS, no mixed content).
// Backend runs on 5433 so v2 coexists with the live Flask app on 5432 until cutover.
// The proxy target is `VITE_API_TARGET` (default :5433) so the SAME config serves both the local
// Windows dev backend AND emma's isolated DEV instance, which points at its own backend on :5434
// (D32 — prod :5433/~/.ctrl-b vs dev :5434/~/.ctrl-b-dev). No hardcoded port branch.
// PWA is wired here; the real manifest/precache tuning is Phase 9 (kept minimal for now).
//
// Bundle analyzer (F12 in docs/UI_AUDIT.md): `npm run build` always writes `dist/stats.html`
// (gzip + brotli sizes). Open it after a build to see exactly what's heavy before deciding
// on F6 (code-splitting) / F7 (lucide-react audit).
export default defineConfig({
  plugins: [
    react(),
    visualizer({
      filename: "dist/stats.html",
      template: "treemap",
      gzipSize: true,
      brotliSize: true,
      // Don't auto-open the report — it's a build artifact, opened on demand.
      open: false,
    }),
    VitePWA({
      // PROMPT — the plugin default, and the mode SwUpdatePrompt (F26) is written for: a new worker
      // installs and WAITS for the toast's refresh tap instead of skipWaiting + force-reloading
      // mid-session (the autoUpdate register client never fires `onNeedRefresh`, so the toast was
      // dead code until this flip — unexercised in prod because SYS-19 meant no worker had ever
      // registered). Explicit rather than omitted so the F26 coupling is visible from here.
      registerType: "prompt",
      devOptions: { enabled: false },
      manifest: {
        name: "ctrl-b",
        short_name: "ctrl-b",
        // Install/splash colors — a D51 DOCUMENTED MIRROR of the DEFAULT theme's `--bg` (cosmos,
        // src/themes/cosmos/tokens.css `#0a0a0d`), kept in step with index.html's <meta name="theme-color">.
        // Static by design: no theme-switch-driven update (recorded as later polish, out of V0).
        theme_color: "#0a0a0d",
        background_color: "#0a0a0d",
        display: "standalone",
        // PWA icon fan-out (F11). Generated by `scripts/gen-pwa-icons.mjs` from
        // `src/assets/vapor-logo.png` (the in-app logo became a bundled asset at D51 V4).
        // - 192/256/512 cover Android home-screen densities + browser install prompts.
        // - The maskable variant fits the brand into the 80% safe zone so Android's circle/squircle
        //   crop never clips it (W3C maskable spec).
        icons: [
          { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
          { src: "/icon-256.png", sizes: "256x256", type: "image/png", purpose: "any" },
          { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
          {
            src: "/icon-maskable-512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
      },
      workbox: {
        // A navigation request under /api is a mistyped endpoint, not an app route — never answer it
        // with the SPA shell. (Unrelated to caching: the ONE cached /api path is the media mount, see
        // `runtimeCaching` below.)
        navigateFallbackDenylist: [/^\/api\//],
        // The plugin default (js/css/html) PLUS vapor's bundled logo (D51 V4 close-out, sweep M2):
        // with cosmos the default, a fresh PWA gone offline may never have fetched the logo before
        // the first switch to vapor — without this entry the mark renders blank. Targeted glob, not
        // image-wide.
        //
        // `dist/stats.html` is the rollup-visualizer BUILD REPORT (~290 KB), not part of the app — the
        // bare `**/*.html` sweeps it into the precache manifest, where it costs every install its size
        // for a file nothing ever requests. Excluded here rather than by narrowing the html glob, so a
        // real future .html entry point is still picked up automatically.
        globPatterns: ["**/*.{js,css,html}", "assets/vapor-logo-*.png"],
        globIgnores: ["**/stats.html"],
        // ── The repo's FIRST runtimeCaching routes (D52/G5, GACHA_PLAN §10.4; council M8 put them
        // here rather than in G0's riders — they touch the PWA update path, and the media caching
        // posture belongs with the media surface).
        //
        // Before these, nothing outside the precache manifest survived offline: every theme's fonts
        // and art fell back to the plain browser HTTP cache. (An earlier note in this file claimed
        // cosmos's art "stays runtime-cached" — it never was; there were no rules at all.) Precaching
        // them instead was the wrong fix: it would charge EVERY install for FOUR themes' assets to
        // make one of them work offline. Cached on first use, an unused theme costs nothing.
        //
        // The two handlers are deliberately different, and the difference is the whole point:
        //  · woff2 are CONTENT-HASHED build outputs — a changed font is a changed filename, so the
        //    cached copy can never be stale. CacheFirst: zero revalidation, ever.
        //  · `/api/media/` files are the OWNER's, mutable under a stable name (they replace
        //    `lyra.webp` over SSH and expect the theme to follow). CacheFirst would pin the old bytes
        //    forever against the mount's own `Cache-Control: no-cache`. StaleWhileRevalidate paints
        //    instantly from cache and repairs itself on the next load — the honest reading of a
        //    revalidate-always resource that must also work offline.
        runtimeCaching: [
          {
            // The build emits every font to `/assets/<name>-<hash>.woff2`.
            urlPattern: /\/assets\/[^/]+\.woff2$/,
            handler: "CacheFirst",
            options: {
              cacheName: "ctrlb-fonts",
              // Five JP weights + the latin faces, with room for a second theme's set before the
              // oldest is evicted; a year, because a hashed name is never re-issued with new bytes.
              expiration: { maxEntries: 40, maxAgeSeconds: 60 * 60 * 24 * 365 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            // A CALLBACK, not a RegExp (Codex F2). Workbox tests a regexp `urlPattern` against the
            // full, unanchored href — so `/api/settings?next=/api/media/gacha/files/` matched, and a
            // live-state response with a media-looking query string would have been cached as art.
            // Matching on the PATHNAME, anchored, and only same-origin, is the only reading that says
            // what was meant. (Workbox serializes the function's source into the SW; it must therefore
            // stay self-contained — no imports, no outer bindings.)
            urlPattern: ({ url, sameOrigin }) =>
              sameOrigin && /^\/api\/media\/[^/]+\/files\//.test(url.pathname),
            handler: "StaleWhileRevalidate",
            options: {
              cacheName: "ctrlb-media",
              // Bounded because these are the owner's own files at whatever size they dropped in
              // (the index warns about a 3.6 MB one; it does not refuse it).
              expiration: { maxEntries: 64, maxAgeSeconds: 60 * 60 * 24 * 30 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
    }),
  ],
  server: {
    host: "0.0.0.0",
    port: 5173,
    // Accept any Host header. Vite (>=5.4) otherwise rejects non-localhost/IP hosts as a
    // DNS-rebinding guard, which blocks reaching the dev server by machine name (e.g.
    // http://corsair:5190) or the Tailscale Serve *.ts.net FQDN. Safe here: tailnet-only,
    // no public bind (AGENTS.md §6 security model).
    allowedHosts: true,
    proxy: { "/api": process.env.VITE_API_TARGET || "http://127.0.0.1:5433" },
  },
});
