// gacha theme fonts (D29 §9.10 / D52 §10.4) — Zen Kaku Gothic New (body + heavy display) + Shippori
// Mincho B1 (the serif JP accent face) + Bungee (the dossier NAME role, added 2026-08-06 off R17; Zen Maru
// Gothic 900 rides along as its token-level alternate). NOT via @fontsource: committed subsets generated by
// `scripts/gen-theme-fonts.mjs` — a frozen subset of the theme's 68 compile-time JP glyphs per weight, plus
// each font's full `latin` subset for the un-freezable Latin (host names, English UI copy). The measured
// rejection that path avoids: ~757 KB of woff2 over ~72 requests on first render, and ~31 MB added to dist.
//
// Same LAZY shape as cosmos/frontier: the @font-face sheet is dynamic-imported into gacha's chunk (an
// inactive theme costs nothing), then we await `document.fonts.load(...)` for the faces used up-front so
// activation paints without a swap flash. Called by `ensureThemeLoaded` (switchTheme.ts) BEFORE the skin
// flips, alongside loadStyles.
//
// The NAME face (the `nameFont` picker) is warmed according to the RESOLVED selection — see `NAME_FACE`.
//
// Each BILINGUAL face is warmed TWICE — once with the default probe text (Latin) and once with the frozen
// JP glyphs — because `faces.css` carries `unicode-range` per face: the Latin and JP files of one weight are
// separate downloads, and a Latin-only probe would leave every JP file unfetched at flip time (the exact
// FOUT this pattern exists to prevent). Zen Kaku 500 is generated but not warmed: no consumer paints at 500
// today, so warming it would block activation on bytes nothing needs (add it here when one does).

import { resolveThemeSetting } from "../../theme-engine/settings";
import { getUI } from "../../store/ui";
import { gachaGlyphSet } from "./copy";

/** Faces with BOTH a jp and a latin file — probed with each. */
const WARM = [
  "400 1em 'Zen Kaku Gothic New'",
  "700 1em 'Zen Kaku Gothic New'",
  "900 1em 'Zen Kaku Gothic New'",
  "600 1em 'Shippori Mincho B1'",
  "800 1em 'Shippori Mincho B1'",
];

/** The NAME face to warm, per `nameFont` value (R17 / the machine-name role) — LATIN-ONLY faces, so one
 *  probe each: the JP probe would match no `unicode-range` and resolve to nothing.
 *
 *  Keyed on the SETTING rather than hardcoded (Codex wave-12 #2), and it is a real bug either way round:
 *  a fixed `Bungee` line made every DEFAULT user download and await a face they never paint, while a
 *  synced `maru` was not warmed at all — so activation could finish before Zen Maru was ready and the
 *  dossier name would land in the fallback and swap under the owner (the exact FOUT this whole module
 *  exists to prevent). `mincho` warms NOTHING extra on purpose: it IS `--font-display`, already covered by
 *  Shippori's two weights in `WARM` above. */
const NAME_FACE: Record<string, string[]> = {
  mincho: [],
  bungee: ["400 1em 'Bungee'"],
  maru: ["900 1em 'Zen Maru Gothic'"],
};

/** The name-face probe list for a `nameFont` value — pure, so the mapping is testable without a document.
 *  An unknown value (a stale sync from a future build) warms nothing rather than guessing: the CSS falls
 *  through to `--font-display` for exactly the same reason, so the two degrade together. */
export function nameFaceProbes(nameFont: string | undefined): string[] {
  return NAME_FACE[nameFont ?? ""] ?? [];
}

export async function loadFonts(): Promise<void> {
  await import("./fonts/faces.css");
  const jp = gachaGlyphSet().join("");
  // The setting, validated through the same resolver every consumer uses — so a stale or corrupt synced
  // value warms the face the app will actually PAINT, not the one it happens to hold. Read at CALL time
  // (never at module init), which is what keeps the settings→registry→theme→fonts import cycle benign.
  const nameFont = resolveThemeSetting("gacha", "nameFont", getUI().themeSettings.gacha?.nameFont);
  try {
    await Promise.all([
      ...WARM.map((f) => document.fonts.load(f)),
      ...WARM.map((f) => document.fonts.load(f, jp)),
      ...nameFaceProbes(typeof nameFont === "string" ? nameFont : undefined).map((f) =>
        document.fonts.load(f),
      ),
    ]);
  } catch {
    /* fall back to font-display behaviour */
  }
}
