// gacha theme fonts (D29 §9.10 / D52 §10.4) — Zen Kaku Gothic New (body + heavy display) + Shippori
// Mincho B1 (the serif JP accent face). NOT via @fontsource: the theme ships COMMITTED subsets generated by
// `scripts/gen-theme-fonts.mjs` — a frozen subset of the theme's 68 compile-time JP glyphs per weight, plus
// each font's full `latin` subset for the un-freezable Latin (host names, English UI copy). The measured
// rejection that path avoids: ~757 KB of woff2 over ~72 requests on first render, and ~31 MB added to dist.
//
// Same LAZY shape as cosmos/frontier: the @font-face sheet is dynamic-imported into gacha's chunk (an
// inactive theme costs nothing), then we await `document.fonts.load(...)` for the faces used up-front so
// activation paints without a swap flash. Called by `ensureThemeLoaded` (switchTheme.ts) BEFORE the skin
// flips, alongside loadStyles.
//
// Each face is warmed TWICE — once with the default probe text (Latin) and once with the frozen JP glyphs —
// because `faces.css` carries `unicode-range` per face: the Latin and JP files of one weight are separate
// downloads, and a Latin-only probe would leave every JP file unfetched at flip time (the exact FOUT this
// pattern exists to prevent). Zen Kaku 500 is generated but not warmed: no consumer paints at 500 today, so
// warming it would block activation on bytes nothing needs (add it here when one does).

import { gachaGlyphSet } from "./copy";

const WARM = [
  "400 1em 'Zen Kaku Gothic New'",
  "700 1em 'Zen Kaku Gothic New'",
  "900 1em 'Zen Kaku Gothic New'",
  "600 1em 'Shippori Mincho B1'",
  "800 1em 'Shippori Mincho B1'",
];

export async function loadFonts(): Promise<void> {
  await import("./fonts/faces.css");
  const jp = gachaGlyphSet().join("");
  try {
    await Promise.all([
      ...WARM.map((f) => document.fonts.load(f)),
      ...WARM.map((f) => document.fonts.load(f, jp)),
    ]);
  } catch {
    /* fall back to font-display behaviour */
  }
}
