import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import { visualizer } from "rollup-plugin-visualizer";

// Dev: proxy /api to the FastAPI backend (single origin → no CORS, no mixed content).
// Backend runs on 5433 so v2 coexists with the live Flask app on 5432 until cutover.
// PWA is wired here; the real manifest/precache tuning is Phase 9 (kept minimal for now).
//
// Bundle analyzer (F12 in docs/UI_AUDIT.md): `npm run build` always writes `dist/stats.html`
// (gzip + brotli sizes). Open it after a build to see exactly what's heavy before deciding
// on F6 (code-splitting) / F7 (lucide-react audit).
export default defineConfig({
  plugins: [
    react(),
    visualizer({
      filename: "dist/stats.html",
      template: "treemap",
      gzipSize: true,
      brotliSize: true,
      // Don't auto-open the report — it's a build artifact, opened on demand.
      open: false,
    }),
    VitePWA({
      registerType: "autoUpdate",
      devOptions: { enabled: false },
      manifest: {
        name: "ctrl-b",
        short_name: "ctrl-b",
        theme_color: "#15171c",
        background_color: "#15171c",
        display: "standalone",
        // PWA icon fan-out (F11). Generated by `scripts/gen-pwa-icons.ps1` from `public/logo.png`.
        // - 192/256/512 cover Android home-screen densities + browser install prompts.
        // - The maskable variant fits the brand into the 80% safe zone so Android's circle/squircle
        //   crop never clips it (W3C maskable spec).
        icons: [
          { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
          { src: "/icon-256.png", sizes: "256x256", type: "image/png", purpose: "any" },
          { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
          { src: "/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
        ],
      },
      workbox: {
        // Never cache /api responses — they're live state and mutations.
        navigateFallbackDenylist: [/^\/api\//],
      },
    }),
  ],
  server: {
    host: "0.0.0.0",
    port: 5173,
    // Accept any Host header. Vite (>=5.4) otherwise rejects non-localhost/IP hosts as a
    // DNS-rebinding guard, which blocks reaching the dev server by machine name (e.g.
    // http://corsair:5190) or the Tailscale Serve *.ts.net FQDN. Safe here: tailnet-only,
    // no public bind (AGENTS.md §6 security model).
    allowedHosts: true,
    proxy: { "/api": "http://127.0.0.1:5433" },
  },
});
