// The INPUT GUARD (D65 / MEDIA_MANAGER_PLAN §4) — what a picked file IS, from its first bytes, and
// whether this app may try to decode it.
//
// PURE and dependency-free, the `lib/media.ts` house shape: it takes the head of a file as bytes and
// answers with facts. Nothing React-, query- or registry-shaped reaches in here, and the tunables it
// judges against arrive as an ARGUMENT (`GuardLimits`) rather than as literals — they live in
// `theme-engine/mediaRegistry.ts`, the module allowed to hold policy (the council H4 rider).
//
// ── why a header reader exists on the CLIENT at all ──────────────────────────────────────────────
//
// `file.size` is a poor proxy for what a decode will cost: a 3 MB PNG can be 100 megapixels of flat
// colour. And the decode is where a phone dies — R54 read both engines' source: **Chrome Android caps
// decoded image bytes at `totalRAM / 25`** and silently IDCT-downscales JPEG to fit while PNG and WebP
// get no cap at all and simply attempt the allocation; **Gecko has no per-image cap whatsoever**. So
// the only guard that exists is ours, it has to run BEFORE `createImageBitmap`, and it therefore has
// to read the dimensions out of the header itself. ~120 lines, zero deps, no decode.
//
// This MIRRORS `app/core/media.py#probe_image` — same three formats, same "a signature alone is not a
// format" rule — and deliberately does not import it (that is server code, and the two ends answer
// different questions: the server describes files already on disk, this decides whether to attempt a
// decode). The fence against the two drifting apart is the shared fixture corpus: real files, one per
// format branch, plus the truncation and lying-extension arms (`tests/lib/imageProbe.test.ts`,
// generated by `scripts/gen-test-images.mjs`).
//
// **Extensions are not consulted, ever.** A picked file's name comes from an Android content URI and
// may be generic or wrong, and it does not matter: the export re-encodes every input, so the name we
// store is minted from the OUTPUT blob's type (§4). A JPEG called `.png` is a perfectly good input.

/** The three formats this surface serves, as the BYTES report them (never the extension). */
export type ImageFormat = "png" | "jpeg" | "webp";

/** A format we RECOGNISE and cannot use, named so the refusal can say which one it was. HEIC is the
 *  realistic one — iPhone shares and Samsung's "HEIF storage" both produce it, Android transcodes
 *  only VIDEO, and neither engine can decode it (R54 §5.2). TIFF and SVG are refused ahead of the
 *  decode for their own reasons: TIFF is undecodable in both engines, and SVG is active content that
 *  a canvas would happily rasterise. */
export type RefusedFormat = "heic" | "tiff" | "svg";

/** What the first bytes of a file say. Every field is independently `null`-able because a header can
 *  be honest about one thing and silent about another — a JPEG whose SOF sits past the head we read
 *  is a real `jpeg` with unknown dimensions, and the decode proof is what settles it. */
export interface ImageHeader {
  format: ImageFormat | null;
  width: number | null;
  height: number | null;
  /** A format named for refusal (see `RefusedFormat`). */
  refused: RefusedFormat | null;
  /** A known signature whose REQUIRED header is not all here — the commonest half-finished copy. The
   *  file may still be growing; either way there is nothing to measure. */
  truncated: boolean;
}

/** The policy this guard judges against — `theme-engine/mediaRegistry.ts#UPLOAD_LIMITS`, structurally.
 *  A parameter rather than an import so `lib/` stays free of the registry (and so every arm of the
 *  test suite can state its own numbers instead of inheriting today's). */
export interface GuardLimits {
  /** The streamed upload cap, from `media.write.max_bytes` — the SERVER's number, read from the
   *  settings snapshot so the client refuses before it wastes an upload on a 413. */
  maxBytes: number;
  /** The most pixels this app will hand a decoder. */
  maxPixels: number;
  /** How much of the file the reader is given. */
  headBytes: number;
}

/** A refusal the owner can act on, or the header we may proceed with. */
export type GuardVerdict = { ok: true; header: ImageHeader } | { ok: false; reason: string };

const MEGAPIXEL = 1_000_000;

/** `2.4 MB` / `640 KB` — sizes in the units the owner's phone shows them in. */
function bytesText(n: number): string {
  return n >= MEGAPIXEL ? `${(n / 1e6).toFixed(1)} MB` : `${Math.round(n / 1000)} KB`;
}

/** Refuse, or admit — the LADDER of §4, in its ruled order: bytes, then pixels, then the formats we
 *  name. The `createImageBitmap` proof is the caller's fourth rung and the catch-all for everything
 *  this cannot see (an AVIF's dimensions live behind ISO-BMFF box parsing, a GIF's frames behind a
 *  decode; both are decodable in both engines, so both are simply attempted).
 *
 *  Every sentence names the NUMBER it failed, because "too big" without the limit is something the
 *  owner cannot act on — they cannot tell whether to crop, re-export or give up. */
export function guardPick(size: number, head: Uint8Array, limits: GuardLimits): GuardVerdict {
  if (size <= 0) return { ok: false, reason: "that file is empty." };
  if (size > limits.maxBytes) {
    return {
      ok: false,
      reason: `that file is ${bytesText(size)} — this app accepts up to ${bytesText(limits.maxBytes)} per image. Export a smaller copy and try again.`,
    };
  }
  const header = readImageHeader(head, size);
  if (header.refused !== null) return { ok: false, reason: refusalText(header.refused) };
  if (header.truncated) {
    return {
      ok: false,
      reason:
        "that file looks incomplete — the picture data stops inside its own header. Try copying it again.",
    };
  }
  if (header.width !== null && header.height !== null) {
    const refusal = pixelRefusal(header.width, header.height, limits.maxPixels);
    if (refusal !== null) return { ok: false, reason: refusal };
  }
  return { ok: true, header };
}

/** The megapixel refusal, or `null` when the size is fine — **one sentence, two callers** (Emma #4).
 *
 *  The header reader cannot measure everything it admits: a JPEG whose frame header sits past the head
 *  we read, and every format this parser deliberately does not dimension (AVIF behind ISO-BMFF boxes, a
 *  GIF behind its own decode), reach `createImageBitmap` with NO pixel count. The decode PROOF is where
 *  their real size first exists, so the cap has to be applied there too — and the owner must meet the
 *  same sentence whichever rung refused them, or the 64 MP contract is only true of the files we happened
 *  to be able to parse. */
export function pixelRefusal(width: number, height: number, maxPixels: number): string | null {
  const pixels = width * height;
  if (pixels <= maxPixels) return null;
  return `that picture is ${width}×${height} (${(pixels / MEGAPIXEL).toFixed(0)} megapixels) — this app decodes up to ${Math.round(maxPixels / MEGAPIXEL)}. Your camera's smaller resolution setting will fit.`;
}

function refusalText(what: RefusedFormat): string {
  if (what === "heic") {
    // The likeliest refusal on the owner's own phone, so it says the FIX rather than the verdict.
    return "that is a HEIC photo, which no browser can open — neither Chrome nor Firefox ships a decoder for it. Switch the camera's storage format to JPEG, or share the photo (sharing converts it).";
  }
  if (what === "tiff")
    return "TIFF images cannot be opened in a browser. Save it as PNG or JPEG first.";
  return "SVG drawings are not accepted here — this surface stores pictures, not documents. Export it as PNG first.";
}

// ── the header reader ────────────────────────────────────────────────────────────────────────────

/** The end of a whole PNG IHDR: the 8-byte signature plus 8+13+4 of chunk (PNG spec §11.2.2). */
const PNG_IHDR_END = 33;
/** The JPEG markers that carry a frame header. `C4`/`C8`/`CC` share the range and are tables. */
const JPEG_SOF = new Set(
  Array.from({ length: 16 }, (_, i) => 0xc0 + i).filter(
    (m) => m !== 0xc4 && m !== 0xc8 && m !== 0xcc,
  ),
);
/** Markers with no length field of their own. */
const JPEG_STANDALONE = new Set([0x01, 0xd8, ...Array.from({ length: 8 }, (_, i) => 0xd0 + i)]);
/** The smallest SOF segment that CONTAINS what is read from it: the length itself, precision, and
 *  the two 16-bit sizes. The parser's minimum, not the format's — that is the claim being checked. */
const JPEG_SOF_MIN_LEN = 7;
/** Per-flavour minimum WebP chunk payload — again the parser's own reach. A chunk declaring less does
 *  not contain the canvas size, so reading it anyway reports a size from bytes outside the chunk. */
const WEBP_MIN_CHUNK: Record<string, number> = { "VP8 ": 10, VP8L: 5, VP8X: 10 };
/** The ISO-BMFF major brands that mean HEIF/HEIC. `avif`/`avis` share the container and are LEFT OUT
 *  deliberately: both engines decode AVIF, so it takes the ordinary path (unmeasured, and guarded by
 *  the byte cap plus the decode proof). */
const HEIF_BRANDS = new Set([
  "heic",
  "heix",
  "hevc",
  "hevx",
  "heim",
  "heis",
  "hevm",
  "hevs",
  "mif1",
  "msf1",
]);

const ascii = (b: Uint8Array, at: number, len: number): string =>
  String.fromCharCode(...b.subarray(at, at + len));

const u32be = (b: Uint8Array, at: number): number =>
  ((b[at] << 24) >>> 0) + (b[at + 1] << 16) + (b[at + 2] << 8) + b[at + 3];
const u16be = (b: Uint8Array, at: number): number => (b[at] << 8) + b[at + 1];
const u16le = (b: Uint8Array, at: number): number => b[at] + (b[at + 1] << 8);
const u32le = (b: Uint8Array, at: number): number =>
  b[at] + (b[at + 1] << 8) + (b[at + 2] << 16) + b[at + 3] * 0x1000000;

/** Format + pixel dimensions from the head of a file. `size` is the WHOLE file's length, which two of
 *  the branches need to tell a complete header from a truncated one.
 *
 *  **A signature alone is not a format** (the `probe_image` rule, kept identical on purpose): an
 *  8-byte PNG signature, a bare `FF D8 FF`, or `RIFF....WEBP` followed by nothing are all files no
 *  browser will render, and reporting a format for them would let a broken picture through the guard
 *  and fail later, in the worker, where there is nothing useful to say about it. */
export function readImageHeader(head: Uint8Array, size: number): ImageHeader {
  const none: ImageHeader = {
    format: null,
    width: null,
    height: null,
    refused: null,
    truncated: false,
  };
  if (head.length >= 8 && ascii(head, 0, 8) === "\x89PNG\r\n\x1a\n") {
    // The IHDR chunk is mandatory, must be FIRST, and is fixed-size (PNG spec §11.2.2). Requiring the
    // WHOLE chunk — its declared length included — is what separates a real header from a file that
    // stops inside one.
    if (head.length >= PNG_IHDR_END && u32be(head, 8) === 13 && ascii(head, 12, 4) === "IHDR") {
      return { ...none, format: "png", width: u32be(head, 16), height: u32be(head, 20) };
    }
    return { ...none, truncated: true };
  }
  if (head.length >= 3 && head[0] === 0xff && head[1] === 0xd8 && head[2] === 0xff) {
    return readJpeg(head, none);
  }
  if (head.length >= 12 && ascii(head, 0, 4) === "RIFF" && ascii(head, 8, 4) === "WEBP") {
    return readWebp(head, size, none);
  }
  // ISO-BMFF: a 4-byte box length, then `ftyp`, then the major brand.
  if (head.length >= 12 && ascii(head, 4, 4) === "ftyp" && HEIF_BRANDS.has(ascii(head, 8, 4))) {
    return { ...none, refused: "heic" };
  }
  if (head.length >= 4 && (ascii(head, 0, 4) === "II*\x00" || ascii(head, 0, 4) === "MM\x00*")) {
    return { ...none, refused: "tiff" };
  }
  if (looksLikeSvg(head)) return { ...none, refused: "svg" };
  return none;
}

/** Walk the marker chain to the first frame header. JPEG is the one format whose size is not at a
 *  fixed offset — EXIF and ICC segments of arbitrary length sit in front of it, which is also why a
 *  head that ends before the SOF yields a real `jpeg` with NO dimensions rather than a refusal: the
 *  file is fine, we simply cannot measure it from here, and the decode proof takes over.
 *
 *  The dimensions read here are the ENCODED ones, before any EXIF rotation. That is the right number
 *  for a decode guard — a rotated photo costs the same pixels either way — and it is why the corpus
 *  carries an `Orientation=6` arm that must report 400×200, not 200×400. */
function readJpeg(head: Uint8Array, none: ImageHeader): ImageHeader {
  const jpeg: ImageHeader = { ...none, format: "jpeg" };
  let i = 2;
  while (i < head.length) {
    if (head[i] !== 0xff) {
      // A conforming stream puts the next marker right here; anything else is padding or junk, so
      // resync rather than give up — the same tolerance `probe_image` walks with.
      i++;
      continue;
    }
    while (i < head.length && head[i] === 0xff) i++; // marker prefixes may repeat as padding
    if (i >= head.length) return jpeg;
    const marker = head[i];
    i++;
    if (JPEG_STANDALONE.has(marker)) continue;
    if (i + 2 > head.length) return jpeg;
    const length = u16be(head, i);
    if (length < 2) return { ...none, truncated: true };
    if (JPEG_SOF.has(marker)) {
      // Two separate things must hold about the DECLARED length: it must CONTAIN the fields being
      // read (a SOF announcing 2 is just the length field, and the "dimensions" after it belong to
      // whatever follows), and the segment must actually be here.
      if (length < JPEG_SOF_MIN_LEN) return { ...none, truncated: true };
      if (i + length > head.length) return jpeg;
      return { ...jpeg, height: u16be(head, i + 3), width: u16be(head, i + 5) };
    }
    i += length;
  }
  return jpeg;
}

/** The three WebP flavours keep the canvas size in three different places (RFC 9649 §2.5), and both
 *  declared lengths must agree with the file — a RIFF announcing more than it contains is truncated. */
function readWebp(head: Uint8Array, size: number, none: ImageHeader): ImageHeader {
  if (head.length < 20) return { ...none, truncated: true };
  const riffSize = u32le(head, 4);
  const chunkSize = u32le(head, 16);
  if (riffSize + 8 > size || chunkSize + 12 > riffSize) return { ...none, truncated: true };
  const fourcc = ascii(head, 12, 4);
  const payload = head.subarray(20);
  if (chunkSize < (WEBP_MIN_CHUNK[fourcc] ?? 0)) return { ...none, truncated: true };
  const webp: ImageHeader = { ...none, format: "webp" };
  if (fourcc === "VP8 " && payload.length >= 10 && ascii(payload, 3, 3) === "\x9d\x01\x2a") {
    // lossy: a 3-byte frame tag, the sync code, then 14-bit width and height
    return { ...webp, width: u16le(payload, 6) & 0x3fff, height: u16le(payload, 8) & 0x3fff };
  }
  if (fourcc === "VP8L" && payload.length >= 5 && payload[0] === 0x2f) {
    // lossless: a signature byte, then 14 bits of width-1 and 14 of height-1
    const bits = u32le(payload, 1);
    return { ...webp, width: (bits & 0x3fff) + 1, height: ((bits >>> 14) & 0x3fff) + 1 };
  }
  if (fourcc === "VP8X" && payload.length >= 10) {
    // extended: 4 flag bytes, then canvas width-1 and height-1 as 3-byte little-endians
    return {
      ...webp,
      width: payload[4] + (payload[5] << 8) + (payload[6] << 16) + 1,
      height: payload[7] + (payload[8] << 8) + (payload[9] << 16) + 1,
    };
  }
  // `RIFF....WEBP` followed by an unknown fourcc: a container we cannot measure. Not a refusal — the
  // decode proof is next — but not a truncation claim either.
  return webp;
}

/** Text that starts an SVG document, allowing a BOM, leading whitespace and an XML declaration.
 *  Sniffed rather than trusted from the extension, because the point is to refuse the BYTES: an SVG
 *  renamed `.png` would otherwise reach a canvas, which rasterises it happily. */
function looksLikeSvg(head: Uint8Array): boolean {
  const text = ascii(head, 0, Math.min(head.length, 512))
    .replace(/^\ufeff/, "")
    .trimStart();
  return text.startsWith("<svg") || (text.startsWith("<?xml") && text.includes("<svg"));
}

/** The head of a file, as the guard wants it. `Blob.slice` is free — a view, not a copy — and it
 *  clamps to the file's own length, so this is only ever a bound on the ArrayBuffer that gets read.
 *  One function so the READ and the limit that sized it can never be spelled apart. */
export async function readHead(file: Blob, limits: GuardLimits): Promise<Uint8Array> {
  return new Uint8Array(await file.slice(0, limits.headBytes).arrayBuffer());
}
